# -*- coding: utf-8 -*-
"""citation_generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IiMo2NYn4k2FkRBJ5p-2daOaSJSjjOvA
"""

def generate_citations(docs):

    citations = []

    for doc in docs:

        act = doc.metadata.get("act", "Unknown Act")
        section = doc.metadata.get("section", "Unknown Section")

        citation = f"{act} - {section}"

        if citation not in citations:
            citations.append(citation)

    return citations