# -*- coding: utf-8 -*-
"""definitions_retriever

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qO_c7qnfRmy5deVP2LJ-laiusEtM0CVa
"""

def detect_act(query, acts_list):
    query_lower = query.lower()
    for act in acts_list:
        if act.lower() in query_lower:
            return act
    return None

def prioritize_definitions(docs):
    """Boost documents containing definitions keywords"""
    keywords = ["definition", "means", "includes"]
    boosted = sorted(docs, key=lambda d: any(k in d.page_content.lower() for k in keywords), reverse=True)
    return boosted