# -*- coding: utf-8 -*-
"""hybrid_search

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S4RMbZp84qckjO-ivc_xNVzFmpgBo0nk
"""

from rank_bm25 import BM25Okapi
import numpy as np

class HybridRetriever:

    def __init__(self, vectorstore, documents):
        self.vectorstore = vectorstore
        self.documents = documents

        tokenized = [doc.page_content.split() for doc in documents]
        self.bm25 = BM25Okapi(tokenized)

    def search(self, query, k=10):
        vector_results = self.vectorstore.similarity_search(query, k=k)
        tokenized_query = query.split()
        bm25_scores = self.bm25.get_scores(tokenized_query)
        top_bm25 = np.argsort(bm25_scores)[-k:]
        bm25_docs = [self.documents[i] for i in top_bm25]
        combined = list({doc.page_content: doc for doc in vector_results + bm25_docs}.values())
        return combined