# -*- coding: utf-8 -*-
"""embed_store

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJyg2h4nWNwWL325IBL0ML94MpA3HO37
"""

from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings
import os

def load_vectorstore():

    embeddings = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2"
    )
    path = "faiss_index"
    if not os.path.exists(path):
        raise ValueError("FAISS index not found. Build embeddings first.")

    db = FAISS.load_local(
        path,
        embeddings,
        allow_dangerous_deserialization=True
    )

    return db
