# -*- coding: utf-8 -*-
"""hybrid_search

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S4RMbZp84qckjO-ivc_xNVzFmpgBo0nk
"""
# src/hybrid_search.py
from rank_bm25 import BM25Okapi
import numpy as np

class HybridRetriever:
    """
    Combines FAISS vector search with BM25 keyword search for hybrid retrieval.
    """
    def __init__(self, vectorstore, documents):
        self.vectorstore = vectorstore
        self.documents = documents

        # Tokenize documents for BM25
        tokenized = [doc.page_content.split() for doc in documents]
        self.bm25 = BM25Okapi(tokenized)

    def search(self, query, k=10, docs=None):
        """
        Retrieve top-k documents using hybrid search.
        If 'docs' is provided, restrict BM25 to this subset.
        """
        if docs is None:
            docs = self.documents

        # Vector search
        vector_results = self.vectorstore.similarity_search(query, k=k)

        # BM25 search
        tokenized_query = query.split()
        tokenized_docs = [doc.page_content.split() for doc in docs]
        bm25 = BM25Okapi(tokenized_docs)
        bm25_scores = bm25.get_scores(tokenized_query)
        top_bm25_idx = np.argsort(bm25_scores)[-k:]
        bm25_docs = [docs[i] for i in top_bm25_idx]

        # Combine and remove duplicates
        combined = list({doc.page_content: doc for doc in vector_results + bm25_docs}.values())
        return combined
