# -*- coding: utf-8 -*-
"""query_rewriter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h9RoDkmfYbtbY4w8cR5oXGnMZ-Q1_BJB
"""

def rewrite_query(query):
    """
    Offline query rewriting:
    Currently returns the original query as a single-item list.
    Could add simple keyword expansion in the future.
    """
    return [query] queries
